theme = "gruvbox-dark"
icons = "material-nf"

[[block]]
block = "speedtest"
format = "{speed_down}"

[[block]]
block = "disk_space"
path = "/home"
info_type = "free"
format = "{icon} {available} free / {total}"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "backlight"

[[block]]
block = "sound"

[[block]]
block = "battery"

[[block]]
block = "pacman"
interval = 10

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
