theme = "gruvbox-dark"
icons = "awesome"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "free"
format = "{icon} {available} free / {total}"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "backlight"

[[block]]
block = "sound"

[[block]]
block = "speedtest"

[[block]]
block = "battery"
format = "{percentage} {time}"

[[block]]
block = "pacman"
interval = 10

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
